DROP DATABASE UCE_TEST
GO
CREATE DATABASE UCE_TEST
GO
USE UCE_TEST
GO
CREATE TABLE Employees(
    Id INT IDENTITY(1,1),
    Name VARCHAR(30) NOT NULL,
    LastName VARCHAR(30) NOT NULL,
    Position VARCHAR(30) NOT NULL,
    BirthDay DATETIME2 NOT NULL,
    DateOfHire DATETIME2 NOT NULL,
    Phone VARCHAR(10) NOT NULL,
    Email VARCHAR(25) NOT NULL,
    CivilStatus VARCHAR(25) NOT NULL,
    Photo IMAGE,
    CONSTRAINT PK_EMPLOYEES_ID PRIMARY KEY (ID),
    CONSTRAINT CK_EMPLOYEES_CIVILSTATUS CHECK (CivilStatus IN('SOLTERO', 'CASADO', 'DIVORCIADO'))
)
GO
CREATE TABLE Directions(
    Id INT IDENTITY(1,1),
    Street VARCHAR(100) NOT NULL,
    Zone VARCHAR(100) NOT NULL,
    PostalCode VARCHAR(6),
    State VARCHAR(50) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    EmployeeId INT NOT NULL,
    CONSTRAINT PK_DIRECTIONS_ID PRIMARY KEY (Id),
    CONSTRAINT FK_DIRECTIONS_EMPLOYEEID FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON DELETE CASCADE
)
GO